/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:00c2e2cc-4384-4fa2-a8b8-aeb975606fa4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_tiHGUbRPC",
    "aws_user_pools_web_client_id": "3vh1e36ul0fn4723af9772susi",
    "oauth": {}
};


export default awsmobile;
